language: python
python:
- 3.6
branches:
  only:
    - master
script:
- python -m unittest -v
deploy:
  provider: heroku
  api_key:
    secure: T732dppi6N7TzYfeFjOiQlxdHG+bEgxQ9KrjWcqXDSLQPKmhUagJztEevdUTT9zHOUyxSDM+W4DZCxg0iL5cJ0Ull58v5mIt8It3S/TXCjt+utjiY4VzgnCJnI4RVYweV4HRi12xvliYVC80gHTHdhE7LNz44o0fV198ozqUcokAOLw6U92IJxhStwd24zK30fAtRUAKDiktLdq+HkKMk1S5zhnwUf6apTQkUk0t0OxnSICfXBuX7r1iCNaICYZIKvjQltR2MDgMonLRIxyjVjXiTH/bOHmpgCRHOHt1+JP0s51Djtl9WDw0wEpEpyrP1luyhtOHyrLZBpRoWeSy1qLWr7rKOWg+KL/1JegkwwatVStM/MAC4cA+efplNLrxf3j7gaken08S0aldLnN4JP/RFY6gw89XMk1Zc3ddC9NnvEzlOOfYLAWWKS8U9rJqffubs39r+3YHyCraZ384yG+vSgSkLBi5zcbqhYtkhnrKXZ7t/Uu0HZfnxNE0bx8Fzoreim9eE+jP1LYn3U8VrKk3/+n/s9gZ1i5oUTFdqRMHQ1D9bFGQJyFg0yWuAniua2hU5CPi4JHOXlc/ddRKgsDbrWrZr/76zNTEET4OUDD9A+nqRRcL4MlVIROOf2hgeVUnYWfkJg7NI8iAxVT5oaI0cv3tzvPn2u5EfobL5hU=
  app: required-labels
  on:
    repo: dimagi/required-labels
